"""Prompt construction for the train-free and QLoRA LLM systems."""

import random

# This instruction was generated by a LLM (fitting for this course) as i am no expert 
# in prompt engineering (or ASL).
INSTRUCTION = (
    "You are a translator from English into American Sign Language (ASL) gloss "
    "notation, following the conventions of the ASLG-PC12 corpus.\n"
    "Rules:\n"
    "- Output ONLY the gloss translation: uppercase tokens separated by single spaces.\n"
    "- Pronouns and pointing signs use the X- prefix (e.g. X-I, X-YOU, X-IT).\n"
    "- Adverbs/adjectives may use the DESC- prefix (e.g. DESC-NEW).\n"
    "- Do not output explanations or lowercase words.\n"
)


def pick_fewshot_examples(train_pairs, k=5, seed=42, max_len=90):
    """Fixed few-shot examples: deterministic, short-to-medium length."""
    rng = random.Random(seed)
    candidates = [p for p in train_pairs if 20 <= len(p["text"]) <= max_len]
    return rng.sample(candidates, k)


def build_chat(text, shots):
    """Chat messages for tokenizer.apply_chat_template."""
    messages = [{"role": "system", "content": INSTRUCTION}]
    for ex in shots:
        messages.append({"role": "user", "content": f"Translate to ASL gloss: {ex['text']}"})
        messages.append({"role": "assistant", "content": ex["gloss"]})
    messages.append({"role": "user", "content": f"Translate to ASL gloss: {text}"})
    return messages


def format_prompt(tokenizer, text, shots):
    return tokenizer.apply_chat_template(
        build_chat(text, shots), tokenize=False, add_generation_prompt=True
    )


def format_training_example(tokenizer, text, gloss):
    """Full chat-formatted training string and its prompt-only prefix (for label masking)."""
    messages = build_chat(text, shots=[])
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    full = prompt + gloss + (tokenizer.eos_token or "")
    return full, prompt
